version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 869935099884.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image for backend...
      - docker build -t fullstack-app-backend .
      - docker tag fullstack-app-backend:latest 869935099884.dkr.ecr.us-east-1.amazonaws.com/fullstack-app-backend:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 869935099884.dkr.ecr.us-east-1.amazonaws.com/fullstack-app-backend:latest

artifacts:
  files:
    - '**/*'